### ISSUE TITLE
Is the mysql password visible through ps?

### ISSUE THREAD

**Issue by 4fd81048a9cd8a3fd43f1f4e52f84181** [quickshiftin/mysqlbkup#10]
Is the database password visible with ps -ef (viewing the mysqldump command line)?

http://stackoverflow.com/questions/9293042/mysqldump-without-the-password-prompt

Is setting up a ~/.my.cnf for the user running the script the best way around this?

Brian

**Comment by quickshiftin** [comment]
Hi Brian,

I presume this issue is fixed with your latest patch. I'm closing the issue. Thanks again for your contribution.
