### ISSUE TITLE
Max Backups Count

### ISSUE THREAD

**Issue by fli-ssullivan** [quickshiftin/mysqlbkup#12]
First off, thanks for a great script!

FYI, on line 141 of mysqlbkup.sh, I think the operator should be '-ge' rather than '-gt'. Otherwise, it will only cull backups when the max is exceeded instead of maintaining the max (because we need to count the backup that is about to occur). Thanks again!

 - S

**Comment by quickshiftin** [comment]
Great catch! I've just pushed a fix on master and cut a new tag (1.5). Thank you for the report!
