### ISSUE TITLE
Support for more granular backups

### ISSUE THREAD

**Issue by meesameesa** [quickshiftin/mysqlbkup#13]
Due to the current way the date format is being set, this script does not support hourly backups (for example) - it would be good if the date format is exposed within the config file. As far as I can see this should be sufficient to support multiple backups within a day.

**Comment by quickshiftin** [comment]
Hi @meesameesa, given the initial stated purpose of the script to be for daily backups I don't view this as an issue. If you want to provide a pull request though I'd be happy to incorporate it as long as the code is clean.
