### ISSUE TITLE
Script can run only once a day

### ISSUE THREAD

**Issue by Hirbod** [quickshiftin/mysqlbkup#14]
Because of the filename. I added 
date=$(date +%F-%H_%M_%S)

instead of single %F, to be able running more backups a day (without overwriting the file everytime)

Would that be fine for you to change that?

**Comment by samwilson** [comment]
This makes sense, and wouldn't interfere with people still only running it once a day (I think).

**Comment by quickshiftin** [comment]
Thanks @VEINHORN , I saw one small issue w/ the PR, please take a look and I can get it merged.

**Comment by quickshiftin** [comment]
Having merged the PR from @VEINHORN I am closing this issue.
